version: '3.4'

services:
  tenhelmets.ms.administration.webapi:
    image: ${DOCKER_REGISTRY-}tenhelmetsmsadministrationwebapi
    build:
      context: .
      dockerfile: TenHelmets.MS.Administration.WebApi\Dockerfile

  tenhelmets.ms.centralmanagement.webapi:
    image: ${DOCKER_REGISTRY-}tenhelmetsmscentralmanagementwebapi
    build:
      context: .
      dockerfile: TenHelmets.MS.CentralManagement.WebApi\Dockerfile


  tenhelmets.ms.construction.webapi:
    image: ${DOCKER_REGISTRY-}tenhelmetsmsconstructionwebapi
    build:
      context: .
      dockerfile: TenHelmets.MS.Construction.WebApi\Dockerfile

  tenhelmets.ms.direction.webapi:
    image: ${DOCKER_REGISTRY-}tenhelmetsmsdirectionwebapi
    build:
      context: .
      dockerfile: TenHelmets.MS.Direction.WebApi\Dockerfile


  tenhelmets.ms.humanresources.webapi:
    image: ${DOCKER_REGISTRY-}tenhelmetsmshumanresourceswebapi
    build:
      context: .
      dockerfile: TenHelmets.MS.HumanResources.WebApi\Dockerfile


  tenhelmets.ms.c.webapi:
    image: ${DOCKER_REGISTRY-}tenhelmetsmscwebapi
    build:
      context: .
      dockerfile: TenHelmets.MS.Operations.WebApi\Dockerfile


  tenhelmets.ms.identityserver.web:
    image: ${DOCKER_REGISTRY-}tenhelmetsmsidentityserverweb
    build:
      context: .
      dockerfile: TenHelmets.MS.IdentityServer.web\Dockerfile

